### ``` Numpy ``` :
 Brief :
 1. In 1995 jim Hugunin created Numeric library for array but it's not that powerful. 
 2. In early 2000's Space Telescope Science Institute (STScI) created Numarray but still not compatible .

3. In 2005 , Numpy was created by Travis Oliphant . Numpy is a library for array manipulation and data analysis .


Numpy is written in c which are compiled and superfast. 

### ``` Numpy Arrays ``` :

1. Numpy arrays are used to store same data type only.
2. performance is much faster
3. Memory efficiency is much higher.
4. Vector operations are easy and fast.

In [121]:
import numpy as np

### ``` Array Creation ```

In [122]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [123]:
arr = [[1,2,3],[4,5,6]] ## 2d array
arr1 = np.array(arr)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

### ``` Array Generation Function ``` :

In [124]:
## to generate array 
arr = np.arange(10) 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
## to generate zeros
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [126]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [127]:
## to generate ones
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [128]:
arr = np.ones((5,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [129]:
## to get no of equally spaced values
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### ``` Random Array Generation Function ``` :

In [130]:
## to get random no
arr = np.random.rand(10) ## to get random float values
arr

array([0.41758653, 0.33611637, 0.7637569 , 0.70281542, 0.38437131,
       0.47223747, 0.91545557, 0.86783478, 0.01896394, 0.12342926])

In [131]:
arr =np.random.randint(1,10,5) ## to get random integer
arr

array([8, 9, 3, 5, 6])

### ``` Array Attributes ```

In [132]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
arr2.shape

(3, 3)

In [134]:
arr2.size

9

In [135]:
arr2.dtype

dtype('int32')

### ``` Array Methods ``` :

In [136]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
arr2.min()

1

In [138]:
arr2.max()

9

In [139]:
## to do sum column wise , axis = 0
np.sum(arr2,axis=0)

array([12, 15, 18])

In [140]:
## to do sum row wise , axis = 1
np.sum(arr2,axis=1)

array([ 6, 15, 24])

In [141]:
arr2.mean()

5.0

In [142]:
arr2.std()

2.581988897471611

In [143]:
arr2.argmax()

8

In [144]:
arr2.argmin()

0

### ``` Reshaping and Resizing Array ```   :

In [145]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [146]:
## to reshape & resize
arr1 = arr.reshape(5,6) ## here 5*6 = 30 means our arr has 30 elements.
## if we give 5*5 , it will give error
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [147]:
## ARray indexing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [148]:
arr[0]

1

In [149]:
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [150]:
arr1[0][:] ## to get 1st row

array([1, 2, 3, 4, 5, 6])

In [151]:
arr1[4][5]

30

In [152]:
arr1[0:3] ## to get first 3 rows

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [153]:
arr1[0:3,0:3] ## to get first 3 rows and first 3 columns

arr1[0:2,1:3] 



array([[2, 3],
       [8, 9]])

In [154]:
arr[::2] ## to get alternate elements

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [155]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [156]:
arr[3:,3:] ## slicing


array([[19, 20],
       [24, 25],
       [29, 30]])

In [157]:
## to get even no 
arr= np.arange(1,31)
bool_index = arr % 2 == 0
bool_index


array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [158]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

### ``` Array Operations ``` :

In [159]:
### arithmetic operations

arr = np.arange(1,6)
print(arr)
arr1 = np.array([6,7,8,9,10])
print(arr1)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [160]:
arr + arr1

array([ 7,  9, 11, 13, 15])

In [161]:
arr * arr1

array([ 6, 14, 24, 36, 50])

In [162]:
arr / arr1

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [163]:
arr ** arr1

array([      1,     128,    6561,  262144, 9765625])

### ``` Broadcasting ``` :

In [164]:
l = [10,20,30,40,50]
b = np.array(l)
b

array([10, 20, 30, 40, 50])

In [166]:
b+10 ## adding 10 to all elements

array([20, 30, 40, 50, 60])

### ``` Deep and Shallow copy ``` : 

In [173]:
### deep copy --> changes in copy will not effect on original
d1 = np.array([10,20,30,40,50])
d2 = d1.copy()
d2[0] = 100
print(d1)
print(d2)

[10 20 30 40 50]
[100  20  30  40  50]


In [174]:
## shallow copy --> changes in copy will effect on original
d1 = np.array([10,20,30,40,50])
d2 = d1
d2[0] = 100
print(d1)
print(d2)

[100  20  30  40  50]
[100  20  30  40  50]


### ``` Matrix operations ``` :

In [178]:
mat1 = np.array([[1,2],[4,5]])
mat2 = np.array([[2,3],[10,0]])
mat1 @ mat2 ## matrix multiplication

array([[22,  3],
       [58, 12]])

In [179]:
np.dot(mat1,mat2) ## matrix multiplication 

array([[22,  3],
       [58, 12]])