### ``` Numpy ``` :
 Brief :
 1. In 1995 jim Hugunin created Numeric library for array but it's not that powerful. 
 2. In early 2000's Space Telescope Science Institute (STScI) created Numarray but still not compatible .

3. In 2005 , Numpy was created by Travis Oliphant . Numpy is a library for array manipulation and data analysis .


Numpy is written in c which are compiled and superfast. 

### ``` Numpy Arrays ``` :

1. Numpy arrays are used to store same data type only.
2. performance is much faster
3. Memory efficiency is much higher.
4. Vector operations are easy and fast.

In [361]:
import numpy as np

### ``` Array Creation ```

In [362]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [363]:
arr = [[1,2,3],[4,5,6]] ## 2d array
arr1 = np.array(arr)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

### ``` Array Generation Function ``` :

In [364]:
## to generate array 
arr = np.arange(10) 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [365]:
## to generate zeros
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [366]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [367]:
## to generate ones
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [368]:
arr = np.ones((5,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [369]:
## to get no of equally spaced values
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### ``` Random Array Generation Function ``` :

In [370]:
## to get random no
arr = np.random.rand(10) ## to get random float values
arr

array([0.31743189, 0.18695398, 0.27485855, 0.46629349, 0.70688399,
       0.12776089, 0.61487226, 0.29670955, 0.15108385, 0.06508131])

In [371]:
arr =np.random.randint(1,10,5) ## to get random integer
arr

array([7, 2, 5, 3, 3])

### ``` Array Attributes ```

In [372]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [373]:
arr2.shape

(3, 3)

In [374]:
arr2.size

9

In [375]:
arr2.dtype

dtype('int32')

### ``` Array Methods ``` :

In [376]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [377]:
arr2.min()

1

In [378]:
arr2.max()

9

In [379]:
## to do sum column wise , axis = 0
np.sum(arr2,axis=0)

array([12, 15, 18])

In [380]:
## to do sum row wise , axis = 1
np.sum(arr2,axis=1)

array([ 6, 15, 24])

In [381]:
arr2.mean()

5.0

In [382]:
arr2.std()

2.581988897471611

In [383]:
arr2.argmax()

8

In [384]:
arr2.argmin()

0

### ``` Reshaping and Resizing Array ```   :

In [385]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [386]:
## to reshape & resize
arr1 = arr.reshape(5,6) ## here 5*6 = 30 means our arr has 30 elements.
## if we give 5*5 , it will give error
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [387]:
## ARray indexing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [388]:
arr[0]

1

In [389]:
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [390]:
arr1[0][:] ## to get 1st row

array([1, 2, 3, 4, 5, 6])

In [391]:
arr1[4][5]

30

In [392]:
arr1[0:3] ## to get first 3 rows

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [393]:
arr1[0:3,0:3] ## to get first 3 rows and first 3 columns

arr1[0:2,1:3] 



array([[2, 3],
       [8, 9]])

In [394]:
arr[::2] ## to get alternate elements

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [395]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [396]:
arr[3:,3:] ## slicing


array([[19, 20],
       [24, 25],
       [29, 30]])

In [397]:
## to get even no 
arr= np.arange(1,31)
bool_index = arr % 2 == 0
bool_index


array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [398]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

### ``` Array Operations ``` :

In [399]:
### arithmetic operations

arr = np.arange(1,6)
print(arr)
arr1 = np.array([6,7,8,9,10])
print(arr1)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [400]:
arr + arr1

array([ 7,  9, 11, 13, 15])

In [401]:
arr * arr1

array([ 6, 14, 24, 36, 50])

In [402]:
arr / arr1

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [403]:
arr ** arr1

array([      1,     128,    6561,  262144, 9765625])

### ``` Broadcasting ``` :

In [404]:
l = [10,20,30,40,50]
b = np.array(l)
b

array([10, 20, 30, 40, 50])

In [405]:
b+10 ## adding 10 to all elements

array([20, 30, 40, 50, 60])

### ``` Deep and Shallow copy ``` : 

In [406]:
### deep copy --> changes in copy will not effect on original
d1 = np.array([10,20,30,40,50])
d2 = d1.copy()
d2[0] = 100
print(d1)
print(d2)

[10 20 30 40 50]
[100  20  30  40  50]


In [407]:
## shallow copy --> changes in copy will effect on original
d1 = np.array([10,20,30,40,50])
d2 = d1
d2[0] = 100
print(d1)
print(d2)

[100  20  30  40  50]
[100  20  30  40  50]


### ``` Matrix operations ``` :

In [408]:
mat1 = np.array([[1,2],[4,5]])
mat2 = np.array([[2,3],[10,0]])
mat1 @ mat2 ## matrix multiplication

array([[22,  3],
       [58, 12]])

In [409]:
np.dot(mat1,mat2) ## matrix multiplication 

array([[22,  3],
       [58, 12]])

In [410]:
## Transpose of matrix
mat1.T

array([[1, 4],
       [2, 5]])

### ``` Advance Operations ``` :

In [411]:
### Stacking array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8]) 

In [412]:
## vertical stacking
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [413]:
## horizontal stacking
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [414]:
## column stacking
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [415]:
## splitting array
a = np.array([1,2,3,4,5,6])
b,c = np.split(a,[3])
print(b)
print(c)

[1 2 3]
[4 5 6]


In [416]:
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [417]:
## split
np.split(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [418]:
## Horizontal split
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [419]:
## to split vertical
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [420]:
## to split horizontal
np.hsplit(c,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [421]:
## Flatten means to convert multi dimensional array into 1d
a = np.array([[1, 2], [3, 4]])
b = a.flatten()
b

array([1, 2, 3, 4])

In [422]:
## Ravel means to convert multi dimensional array into 1d
a = np.array([[1, 2], [3, 4]])
b = a.ravel()
b

array([1, 2, 3, 4])

## ``` Excercise ```

1. Suduko

In [423]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [424]:
b = np.sum(s , axis = 1)
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


General Questions



In [425]:

import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [426]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [427]:
#Find the average age of students.
np.mean(data[:,0])

18.4

In [428]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [429]:
#Find the highest Science mark.
s_mark = data[:,2]
s_mark.max()

95

In [430]:
## get details of the student who scored more than 90 in math
data[data[:,1]>90]

array([[19, 92, 88]])

In [431]:
## increase math marks of all students by 5
m_mark = data[:,1]
m=m_mark+5
m

array([90, 97, 81, 70, 95])

In [432]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [433]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis = 0)

array([81.6, 83.2])

In [434]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>= 80) & (data[:,2] >= 80)] 

array([[19, 92, 88],
       [20, 90, 85]])

In [435]:
#Replace all Science marks < 75 with 0.
d = data[:,2][data[:,2] < 75  ] = 0
d
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])